import { Brands } from "@/types";

export const BRANDS_DATA: Brands[] = [
  {
    id: 1,
    name: "Tube Store",
    location: "326 Bomo way Alagomeji, Nassarawa, abuja, Nigeria",
    mobile: "07015487433",
    logo: "/images/brands/brand-1.png",
    image:"/images/bg/card-1.avif",
    category: "Electronics",
  },
  {
    id: 2,
    name: "Samsung",
    location: "326 Bomo way Alagomeji, Nassarawa, abuja, Nigeria",
    mobile: "07015487433",
    logo: "/images/brands/brand-2.png",
    image:"/images/bg/card-2.avif",
    category: "Electronics",
  },
  {
    id: 3,
    name: "Nike",
    location: '326 Bomo way Alagomeji, Nassarawa, abuja, Nigeria',
    mobile: '07015487433',
    logo: "/images/brands/brand-3.png",
    image:"/images/bg/card-3.avif",
    category: "Fashion",
  },
  {
    id: 4,
    name: "Adidas",
    location: '326 Bomo way Alagomeji, Nassarawa, abuja, Nigeria',
    mobile: '07015487433',
    logo: "/images/brands/brand-1.png",
    image:"/images/bg/card-4.avif",
    category: "Fashion",
  },
  {
    id: 5,
    name: "Coca-Cola",
    location: '326 Bomo way Alagomeji, Nassarawa, abuja, Nigeria',
    mobile: '07015487433',
    logo: "/images/brands/brand-2.png",
    image:"/images/bg/card-1.avif",
    category: "Food",
  },
  {
    id: 6,
    name: "Pepsi",
    location: '326 Bomo way Alagomeji, Nassarawa, abuja, Nigeria',
    mobile: '07015487433',
    logo: "/images/brands/brand-3.png",
    image:"/images/bg/card-2.avif",
    category: "Food",
  },
  {
    id: 7,
    name: "Sony",
    location: '326 Bomo way Alagomeji, Nassarawa, abuja, Nigeria',
    mobile: '07015487433',
    logo: "/images/brands/brand-1.png",
    image:"/images/bg/card-3.avif",
    category: "Electronics",
  },
  {
    id: 8,
    name: "Puma",
    location: '326 Bomo way Alagomeji, Nassarawa, abuja, Nigeria',
    mobile: '07015487433',
    logo: "/images/brands/brand-2.png",
    image:"/images/bg/card-4.avif",
    category: "Fashion",
  },
  {
    id: 9,
    name: "Nestle",
    location: '326 Bomo way Alagomeji, Nassarawa, abuja, Nigeria',
    mobile: '07015487433',
    logo: "/images/brands/brand-3.png",
    image:"/images/bg/card-1.avif",
    category: "Food",
  },
  {
    id: 10,
    name: "Pepsi",
    location: '326 Bomo way Alagomeji, Nassarawa, abuja, Nigeria',
    mobile: '07015487433',
    logo: "/images/brands/brand-1.png",
    image:"/images/bg/card-2.avif",
    category: "Food",
  },
  {
    id: 11,
    name: "Sony",
    location: '326 Bomo way Alagomeji, Nassarawa, abuja, Nigeria',
    mobile: '07015487433',
    logo: "/images/brands/brand-2.png",
    image:"/images/bg/card-3.avif",
    category: "Electronics",
  },
  {
    id: 12,
    name: "Puma",
    location: '326 Bomo way Alagomeji, Nassarawa, abuja, Nigeria',
    mobile: '07015487433',
    logo: "/images/brands/brand-2.png",
    image:"/images/bg/card-4.avif",
    category: "Fashion",
  },
  {
    id: 13,
    name: "Nestle",
    location: '326 Bomo way Alagomeji, Nassarawa, abuja, Nigeria',
    mobile: '07015487433',
    logo: "/images/brands/brand-3.png",
    image:"/images/bg/card-1.avif",
    category: "Food",
  },
];
