import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import "./custom.css";
import Header from "@/components/common/Header";
import Footer from "@/components/common/Footer";
import Motion from "@/components/ui/Motion";
import StoreProvider from "./StoreProvider";
import ClientBreadcrumb from "@/utils/ClientBreadcrumb";
import { ReactNode } from "react";
import { Toaster } from "react-hot-toast";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} font-sans antialiased`}>
        <StoreProvider>
          <Header />
          <ClientBreadcrumb />
          <Toaster position="top-center" />
          <Motion>{children}</Motion>
          <Footer />
        </StoreProvider>
      </body>
    </html>
  );
}
